version: '3.7'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html 
      
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
        - DEFAULT_EMAIL=andrew.damario@mail.utoronto.ca
        
  frontend:
    # image: ghcr.io/UTSCC09/frontend-andrewaclear
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=www.slackertracker.software
      - LETSENCRYPT_HOST=www.slackertracker.software
      
  backend:
    # image: ghcr.io/UTSCC09/backend-andrewaclear
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.www.slackertracker.software
      - LETSENCRYPT_HOST=api.www.slackertracker.software
     